### ISSUE TITLE
passive eventListener issue as of Chrome 56

### ISSUE THREAD

**Issue by lukemelia** [jgwhite/ember-sortable#130]
Chrome 56 makes a change so that you must pass `passive: false` to touchstart & touchmove events if you want to be able to successfully call `evt.preventDefault()`. Otherwise the `preventDefault` call is ignored, resulting in the div or page scrolling whilst dragging the sortable item. This can be seen on the demo site: 
 
![image](https://cloud.githubusercontent.com/assets/353/22850378/5b34eb9e-efd6-11e6-8d6c-71621fab011c.png)

**Comment by jgwhite** [comment]
Wow, that I'd read about passive listeners but this kinda seems like a "break the web" change. Easy to patch I guess.

**Comment by acburdine** [comment]
Yup - I'll get a fix in for this ASAP.

**Comment by acburdine** [comment]
@lukemelia I looked over our codebase, and there's only one call to `preventDefault`, and that's within the `touchStart` event handler provided by Ember itself. I know there's a way to disable event handlers altogether in Ember, but as far as I know not a way to explicitly make an event `{passive:false}` as far as Ember is concerned.

Is there something that this library can do to work around that issue? I'm going to open an issue on Ember's repo to get some feedback there, but if there's nothing we can do at the moment then I'll probably close this.

**Comment by acburdine** [comment]
On second thought I had the idea of just bypassing Ember's default provided touch events altogether, but as it turns out a) jQuery doesn't provide a way to add `{passive: false}` to any event listeners (as far as I could tell - I searched for several issues and there doesn't seem to be any progress on current jQuery versions) and b) doing things the manual way (via `document.addEventListener`) would require ember-sortable to maintain a knowledge of what browser the user is running in and only supply `{passive: false}` if they're in Chrome. Although I haven't necessarily tested it - the third value passed to `document.addEventListener` was for a long time a boolean - so I don't know how other browsers that don't support an options hash as a third parameter would handle it. (according to the MDN spec and http://caniuse.com/#feat=passive-event-listener it's really only Edge, IE, and maybe Safari, but I'd rather not break support for those if it could be avoided)

Ultimately, it's possible but not trivial to fix this manually, so I'll probably wait until there's some feedback/progress in Ember itself before trying to fix this /cc @jgwhite

**Comment by jgwhite** [comment]
I think that solution sounds good but I'm amazed that Chrome/W3C aren't getting pushback on this.

**Comment by jgwhite** [comment]
Holding off until we know more sounds good too.

**Comment by lukemelia** [comment]
Thanks for digging in guys. I'm happy to share code that I'm using to fix similar stuff internal to Yapp once I get everything working.

**Comment by krisselden** [comment]
@jgwhite if you apply `touch-action: none` to the draggable area it fixes it, but you need to apply it just to the handle specifically in the scrollable list example.

**Comment by acburdine** [comment]
@krisselden thanks for the suggestion - that seems to have done it. Will release a 1.9.2 version with the fix in as soon as I can

**Comment by acburdine** [comment]
Fix released as part of ember-sortable 1.9.2 😄

**Comment by lukemelia** [comment]
Thanks for jumping on this @acburdine! What are the cross-browser implications here? If I'm reading [this](http://caniuse.com/#search=touch-action) right, `touch-action: none` is not yet supported in current versions of Firefox and Safari.

**Comment by acburdine** [comment]
Oh shoot - removing the `preventDefault` breaks Firefox and safari then 😞  Time to fix again!

**Comment by acburdine** [comment]
Alright - should be _actually_ fixed with 1.9.3 😅 Let me know if you experience any more issues

**Comment by RByers** [comment]
Sorry for the trouble, thanks for fixing this!  There's some details on the Chrome change [here](https://developers.google.com/web/updates/2017/01/scrolling-intervention) if anyone is interested.

**Comment by jgwhite** [comment]
@RByers thanks so much commenting, it means a lot 🙂

**Comment by RByers** [comment]
jgwhite@ thank you, your response has inspired me to [encourage our team](https://groups.google.com/a/chromium.org/forum/#!topic/intervention-dev/_0eSO-NjULo) to do this sort of GitHub-based outreach anytime we have a risky breaking change like this!
