### ISSUE TITLE
After sorting the list too fast, whole list is flickering

### ISSUE THREAD

**Issue by Vazgen7788** [jgwhite/ember-sortable#71]
In demo when I drag the last element to the window top fast and leave it (faster than sorting animation) the list is jumping little than going back.

**Comment by jgwhite** [comment]
Thanks for the report. Which browser?

**Comment by Vazgen7788** [comment]
Both in Google Chrome and Firefox

**Comment by jgwhite** [comment]
On which OS? Any chance you could record a screencast? If it’s the effect I *think* you’re describing it’s very well difficult to code around.

**Comment by Vazgen7788** [comment]
On Mac is works correct but on Ubuntu and on Windows not correct... I will record a video and send you.

**Comment by Vazgen7788** [comment]
See Here https://drive.google.com/file/d/0B_RF9abla7pvLVRQdlo2eTNxQ2s/view?pli=1

**Comment by jgwhite** [comment]
Thanks. This is due to the way Glimmer re-uses existing elements to make the minimal possible set of changes to the DOM. There is already [some code][1] in ember-sortable to counteract it and it boils to letting the DOM “settle” before restoring default CSS.

[1]: https://github.com/jgwhite/ember-sortable/blob/9bb90f3bb2b02183f35be2dd7acf2ebb17068d3e/addon/components/sortable-group.js#L129-L141

**Comment by Vazgen7788** [comment]
Do you plan to fix this? We are using your addon in our custom cms and actually we didn't found any viable alternative to this addon and it seems only issue with your addon is this one in our case, so we plan to stick  with you :)

**Comment by jgwhite** [comment]
Yes, this will definitely be fixed. I can’t promise any timeline. If you or your team are interested in trying to submit a fix I’d be happy to help you get started.
