### ISSUE TITLE
Reorder does not save after item is released

### ISSUE THREAD

**Issue by jlommori** [jgwhite/ember-sortable#99]
Hello

I have implemented ember-sortable for a list of questions to be reordered however, after I try to sort the list, it doesn't seem to update the view. Each of the items in my list have a "position" field that stores a number for what order it should sort in. When the route is loaded, the model is sorted by this position field. 

When dragging the items around, they update the model without a problem, however the view never updates so the items don't reorder until the page is reloaded.

Any ideas of how to manually trigger the view update when an item is sorted?

**Comment by scottmessinger** [comment]
@jlommori Are you sorting the the model in the route? If so, I wonder if you sorted in the component it would update. Can you post the router/component code?

**Comment by raelbr** [comment]
When you drag an item, than its positions reverts to the default (as if you had not dragged the item) or you need to receive an updated position from server?

If you have followed the provided example for ember-sortable's github page you shouldn't  have getting trouble with the first case, but if the second case is what is bugging you, then you should try a Route.refresh() and you will probaly need to set your resource object manualy with the updated model data

**Comment by acburdine** [comment]
@jlommori - I just tested this and was not able to reproduce the error you're seeing. Using the basic usage given in the readme, I was able to successfully sort items programmatically in the controller and they would update in the view, which would still let me drag and reorder them as well. Here's the [twiddle](https://ember-twiddle.com/6fc8eb235a59f7451dc6247202eb1133?openFiles=templates.application.hbs%2C) for reference.

Likely your issue is related to your individual setup. Based on the issue as you described it you may  not be sorting your model correctly. Regardless, this isn't an issue with ember-sortable itself :smile:
